language: node_js
node_js:
- '0.10'
deploy:
  provider:heroku
  api_key:
    secure: docl4PtAjSo2Guoqm2XEPuw9R1FhbYoXPraTY5TkWaIbhhMbL8PxazR4WyB3ajmrY8WpA/6WPqY2HS/GWW5z2FLVz27z5b0MVcZZRHCFMFnlET4KY/fRjJDqUx9nFkTN67Z1JaN+APe8v6dlfv+h81td9ZzRGz+xRQ2VHslAEec=
  app:
  	master: axemaze
  	devdb: axemaze-db
branches:
  only:
  - master
  - dbdev
