language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt
deploy:
  provider: heroku
  api_key:
    secure: Bn9D95ynvBt200S4ZxH6ktWZQ84PUO4lbAD6l6+LH7KKOKUtiSTR22ySlBDZfsfwk5uXZehQYGQ19whOON3rxEGc4GtKrLnd69hNkWfvhW1yDAMDaGG8sV5lLa6b4CMmnkF+SvchGl3GGD0tQmufKEM+L58U5rQBKV/EFDe+vfA=
  app:
    master: axemaze
    dbdev: axemaze-db
branches:
  only:
  - master
  - dbdev
